### ISSUE TITLE
App crashing on A14 qpr3 beta 2

### ISSUE THREAD

**Issue by shailantani** [zacharee/InstallWithOptions#12]
Whenever the app is opened the app crashes.
I'm running on pixel 7a 
Here's the crash log:

[Device Brand]: google
[Device Model]: Pixel 7a
[Display]: AP21.240216.010
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_IN
[Process ID]: 8961
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: dev.zwander.installwithoptions
[Version Name]: 0.4.0
[Version Code]: 7
[Target SDK]: 34
[Min SDK]: 24
[Error Type]: JVM
[Crash Time]: 2024-03-18T15:29:56.638
[Stack Trace]:
java.lang.IllegalStateException: scroll observation scope does not exist
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager.checkForContentCapturePropertyChanges(AndroidContentCaptureManager.android.kt:332)
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager.contentCaptureChangeChecker$lambda$0(AndroidContentCaptureManager.android.kt:145)
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager.$r8$lambda$1XDFQ87DMU0Pr1CSBqiV4PdF6bM(Unknown Source:0)
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8583)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by bagarwa** [comment]
Same crash on Pixel 7 Pro, Android 14 QPR3 Beta 2.1 . Using root, not sizuku.

**Comment by swiftness427** [comment]
New version of
*SD Maid 2/SE - System Cleaner v0.23.3-beta0 [Beta] [FOSS] [Pro]* just
dropped .

https://devuploads.com/gdakvnef6vlu

**Comment by bagarwa** [comment]
Didn't quite get what SD Maid has got to do with InstallWithOptions. I already have SD Maid SE and that's working fine.
