### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Antlersandsunbeams** [zacharee/InstallWithOptions#4]
Android 14, QPR2. Installs fine, crashes before menu even loads.

**Comment by zacharee** [comment]
Can you provide a log?

**Comment by drogga** [comment]
FATAL EXCEPTION: main
Process: dev.zwander.installwithoptions, PID: 31796
java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
	at android.media.ImageReader.nativeImageSetup(Native Method)
	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:439)
	at android.media.ImageReader.acquireNextImage(ImageReader.java:493)
	at android.media.ImageReader.acquireLatestImage(ImageReader.java:386)
	at androidx.compose.ui.graphics.layer.LayerManager.persistLayers$lambda$2$lambda$1(LayerManager.android.kt:98)
	at androidx.compose.ui.graphics.layer.LayerManager.$r8$lambda$7gVcSQwR-hnDyZM7SbqTfv4OyS0(Unknown Source:0)
	at androidx.compose.ui.graphics.layer.LayerManager$$ExternalSyntheticLambda0.onImageAvailable(D8$$SyntheticClass:0)
	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by drogga** [comment]
**from v0.6.0:**
FATAL EXCEPTION: main
Process: dev.zwander.installwithoptions, PID: 31796
java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
	at android.media.ImageReader.nativeImageSetup(Native Method)
	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:439)
	at android.media.ImageReader.acquireNextImage(ImageReader.java:493)
	at android.media.ImageReader.acquireLatestImage(ImageReader.java:386)
	at androidx.compose.ui.graphics.layer.LayerManager.persistLayers$lambda$2$lambda$1(LayerManager.android.kt:98)
	at androidx.compose.ui.graphics.layer.LayerManager.$r8$lambda$7gVcSQwR-hnDyZM7SbqTfv4OyS0(Unknown Source:0)
	at androidx.compose.ui.graphics.layer.LayerManager$$ExternalSyntheticLambda0.onImageAvailable(D8$$SyntheticClass:0)
	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**v0.5.0 Doesn't crash.**

**Comment by zacharee** [comment]
It's a bug in Compose: https://issuetracker.google.com/issues/344633766

**Comment by zacharee** [comment]
There isn't anything I can do.

**Comment by drogga** [comment]
That's really unfortunate..., in that case what should be the actual current requirements for the moment - A.9, 10 or 11+ ? (originally A.7+, but stuck with v0.5.0 on A.8) because of / due to this, until / if fixed by G.

**Comment by drogga** [comment]
Maybe you can/should revert https://github.com/zacharee/InstallWithOptions/commit/04988086fdd25ebef69b2b0dde64f04fe300bb96 ...?

**Comment by drogga** [comment]
> _Status: Won't Fix (Obsolete)_
> Layer persistence was disabled, so rendering into the offscreen surface backed by an ImageReader no longer occurs.

...I hope it's fixed (indirectly), because even the Play Store app crashes on/in those systems whre IWO does because of this Compose bug.
